server:
  port: 9095

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  application:
    name: auth-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: true