server:
  port: 9096

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  application:
    name: post-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_post1?createDatabaseIfNotExist=false&allowPublicKeyRetrieval=true&useSSL=false
    username: ENC(NWQUYyNmuP7u9CyiNcjOLMp7HNTDHKrk)
    password: ENC(r1V6GiDXIJ13B5ZltjhMHRIWm+wtRDRo)
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    open-in-view: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    string-output-type: base64