server:
  port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  application:
    name: organization-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_orgniazation?allowPublicKeyRetrieval=true&useSSL=false
    username: ENC(NWQUYyNmuP7u9CyiNcjOLMp7HNTDHKrk)
    password: ENC(r1V6GiDXIJ13B5ZltjhMHRIWm+wtRDRo)
  jpa:
    hibernate:
     ddl-auto: update
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    open-in-view: false
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  devtools:
    livereload:
      enabled: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    string-output-type: base64