spring:
  application:
    name: organization-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
server:
  port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/