spring:
  application:
    name: gateway-service
  banner:
    location: banner/banner.txt
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      fetchRegistry: true

zuul:
  ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000
    eager-load:
      enabled: true
  host:
    socket-timeout-millis: 120000
    connect-timeout-millis: 120000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 120000
        timeout:
          enabled: false

niws:
  loadbalancer:
    availabilityFilteringRule:
      activeConnectionsLimit: 2147483647