spring:
  application:
    name: gateway-service
  banner:
    location: banner/banner.txt
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      fetchRegistry: true
# Test service mapping
zuul:
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
    organization-service:
      path: /organization-service/**
      serviceid: organization-service
